ALTER TABLE users
    ADD COLUMN password VARCHAR(255) AFTER email,
    ADD COLUMN phone VARCHAR(20) AFTER profile_picture,
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at,
    MODIFY COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
