-- Sample assets, bookings, tickets, and supporting data.
-- Runs AFTER V7 (resource_types table + type_id FK exist).

-- RESOURCE TYPES (seed known types)
INSERT IGNORE INTO resource_types (name) VALUES
    ('Smart Classroom'),
    ('Design Studio'),
    ('Computer Lab'),
    ('Network Lab'),
    ('Electronics Lab'),
    ('Seminar Room'),
    ('Projector'),
    ('Innovation Hub'),
    ('Sound System');

-- ASSETS (10) — uses type_id FK
INSERT IGNORE INTO assets (name, type_id, status, capacity, location_id, image_url, description)
VALUES
    ('A102 SMART CLASSROOM',        (SELECT id FROM resource_types WHERE name = 'Smart Classroom'  LIMIT 1), 'ACTIVE',          80, (SELECT id FROM locations WHERE name = 'A102 SMART CLASSROOM'         LIMIT 1), NULL, 'Fully equipped smart classroom with interactive whiteboard and A/V system.'),
    ('A305 DESIGN STUDIO',          (SELECT id FROM resource_types WHERE name = 'Design Studio'    LIMIT 1), 'ACTIVE',          45, (SELECT id FROM locations WHERE name = 'A305 DESIGN STUDIO'           LIMIT 1), NULL, 'Creative space with drawing tablets, large-format printers, and workstations.'),
    ('B401 COMPUTER LAB',           (SELECT id FROM resource_types WHERE name = 'Computer Lab'     LIMIT 1), 'ACTIVE',          60, (SELECT id FROM locations WHERE name = 'B401 COMPUTER LAB'            LIMIT 1), NULL, 'General-purpose computing lab with 60 high-spec workstations.'),
    ('B702 NETWORK LAB',            (SELECT id FROM resource_types WHERE name = 'Network Lab'      LIMIT 1), 'ACTIVE',          40, (SELECT id FROM locations WHERE name = 'B702 NETWORK LAB'             LIMIT 1), NULL, 'Dedicated networking lab with Cisco routers, switches, and patch panels.'),
    ('C203 ELECTRONICS LAB',        (SELECT id FROM resource_types WHERE name = 'Electronics Lab'  LIMIT 1), 'OUT_OF_SERVICE',   36, (SELECT id FROM locations WHERE name = 'C203 ELECTRONICS LAB'         LIMIT 1), NULL, 'Electronics practical lab — currently under maintenance.'),
    ('C110 SEMINAR ROOM',           (SELECT id FROM resource_types WHERE name = 'Seminar Room'     LIMIT 1), 'ACTIVE',          55, (SELECT id FROM locations WHERE name = 'C110 SEMINAR ROOM'            LIMIT 1), NULL, 'Seminar room with wireless mic system and presentation console.'),
    ('D512 4K LASER PROJECTOR',     (SELECT id FROM resource_types WHERE name = 'Projector'        LIMIT 1), 'ACTIVE',           1, (SELECT id FROM locations WHERE name = 'D512 MEETING ROOM'            LIMIT 1), NULL, 'Portable 4K laser projector available for booking in meeting spaces.'),
    ('E904 AI INNOVATION HUB',      (SELECT id FROM resource_types WHERE name = 'Innovation Hub'   LIMIT 1), 'ACTIVE',          70, (SELECT id FROM locations WHERE name = 'E904 AI INNOVATION HUB'       LIMIT 1), NULL, 'Open innovation hub with GPU workstations and collaborative zones.'),
    ('F1102 INTERACTIVE PROJECTOR', (SELECT id FROM resource_types WHERE name = 'Projector'        LIMIT 1), 'ACTIVE',           1, (SELECT id FROM locations WHERE name = 'F1102 LIBRARY DISCUSSION ROOM' LIMIT 1), NULL, 'Short-throw interactive projector for library discussion room.'),
    ('G1203 LINE ARRAY SOUND SYSTEM',(SELECT id FROM resource_types WHERE name = 'Sound System'   LIMIT 1), 'OUT_OF_SERVICE',    1, (SELECT id FROM locations WHERE name = 'G1203 ROOFTOP EVENT SPACE'    LIMIT 1), NULL, 'Professional line-array PA system for outdoor events — currently offline.');

-- BOOKINGS (10)
INSERT IGNORE INTO bookings (
    asset_id, requested_by, booking_date, start_time, end_time,
    purpose, headcount, status, reviewed_by, review_reason
)
VALUES
    ((SELECT id FROM assets WHERE name = 'B401 COMPUTER LAB'            LIMIT 1), (SELECT id FROM users WHERE email = 'isuri.jayawardena@smartcampus.com'     LIMIT 1), '2026-04-21', '09:00:00', '11:00:00', 'Programming Fundamentals Lab Session',         52, 'APPROVED', (SELECT id FROM users WHERE email = 'kavinda.mendis@smartcampus.com' LIMIT 1), 'Room and capacity confirmed'),
    ((SELECT id FROM assets WHERE name = 'A102 SMART CLASSROOM'         LIMIT 1), (SELECT id FROM users WHERE email = 'chamod.perera@smartcampus.com'          LIMIT 1), '2026-04-22', '10:00:00', '12:00:00', 'Data Structures Revision Workshop',            68, 'PENDING',  NULL, NULL),
    ((SELECT id FROM assets WHERE name = 'A305 DESIGN STUDIO'           LIMIT 1), (SELECT id FROM users WHERE email = 'shehani.wickramasinghe@smartcampus.com' LIMIT 1), '2026-04-23', '13:00:00', '15:00:00', 'UI UX Prototyping Lab',                        32, 'APPROVED', (SELECT id FROM users WHERE email = 'kavinda.mendis@smartcampus.com' LIMIT 1), 'No schedule conflicts'),
    ((SELECT id FROM assets WHERE name = 'C203 ELECTRONICS LAB'         LIMIT 1), (SELECT id FROM users WHERE email = 'dilan.gunasekara@smartcampus.com'       LIMIT 1), '2026-04-24', '08:30:00', '10:00:00', 'Embedded Systems Circuit Practical',           28, 'REJECTED', (SELECT id FROM users WHERE email = 'kavinda.mendis@smartcampus.com' LIMIT 1), 'Lab currently under maintenance'),
    ((SELECT id FROM assets WHERE name = 'C110 SEMINAR ROOM'            LIMIT 1), (SELECT id FROM users WHERE email = 'malith.senaratne@smartcampus.com'       LIMIT 1), '2026-04-25', '14:00:00', '16:00:00', 'Final Year Project Proposal Presentation',     48, 'APPROVED', (SELECT id FROM users WHERE email = 'kavinda.mendis@smartcampus.com' LIMIT 1), 'Approved by academic office'),
    ((SELECT id FROM assets WHERE name = 'D512 4K LASER PROJECTOR'      LIMIT 1), (SELECT id FROM users WHERE email = 'pavithra.abeywickrama@smartcampus.com'  LIMIT 1), '2026-04-26', '09:30:00', '11:00:00', 'Projector reservation for QA review',           1, 'APPROVED', (SELECT id FROM users WHERE email = 'kavinda.mendis@smartcampus.com' LIMIT 1), 'Projector slot confirmed'),
    ((SELECT id FROM assets WHERE name = 'E904 AI INNOVATION HUB'       LIMIT 1), (SELECT id FROM users WHERE email = 'isuri.jayawardena@smartcampus.com'      LIMIT 1), '2026-04-27', '11:00:00', '13:00:00', 'Machine Learning Club Hack Session',           58, 'PENDING',  NULL, NULL),
    ((SELECT id FROM assets WHERE name = 'F1102 INTERACTIVE PROJECTOR'  LIMIT 1), (SELECT id FROM users WHERE email = 'chamod.perera@smartcampus.com'          LIMIT 1), '2026-04-28', '15:00:00', '17:00:00', 'Interactive projector reservation for demo',    1, 'APPROVED', (SELECT id FROM users WHERE email = 'kavinda.mendis@smartcampus.com' LIMIT 1), 'Equipment checkout approved'),
    ((SELECT id FROM assets WHERE name = 'B702 NETWORK LAB'             LIMIT 1), (SELECT id FROM users WHERE email = 'shehani.wickramasinghe@smartcampus.com' LIMIT 1), '2026-04-29', '07:30:00', '09:30:00', 'Computer Networks Router Configuration Lab',   34, 'APPROVED', (SELECT id FROM users WHERE email = 'kavinda.mendis@smartcampus.com' LIMIT 1), 'Technician support available'),
    ((SELECT id FROM assets WHERE name = 'G1203 LINE ARRAY SOUND SYSTEM' LIMIT 1),(SELECT id FROM users WHERE email = 'dilan.gunasekara@smartcampus.com'       LIMIT 1), '2026-04-30', '16:00:00', '18:00:00', 'Sound system reservation for open air rehearsal', 1, 'REJECTED', (SELECT id FROM users WHERE email = 'kavinda.mendis@smartcampus.com' LIMIT 1), 'Equipment is currently inactive');

-- TICKETS (10)
INSERT IGNORE INTO tickets (
    reported_by, asset_id, priority, title, description, contact,
    status, assigned_to, resolution_notes, rejection_reason, resolved_at, closed_at
)
VALUES
    ((SELECT id FROM users WHERE email = 'isuri.jayawardena@smartcampus.com'     LIMIT 1), (SELECT id FROM assets WHERE name = 'B401 COMPUTER LAB'            LIMIT 1), 'HIGH',   'Projector Power Failure in B401',          'Ceiling projector does not turn on during lectures.',                    'ticket001@smartcampus.com', 'OPEN',        (SELECT id FROM users WHERE email = 'kavinda.mendis@smartcampus.com'  LIMIT 1), NULL,                                          NULL,                          NULL, NULL),
    ((SELECT id FROM users WHERE email = 'chamod.perera@smartcampus.com'          LIMIT 1), (SELECT id FROM assets WHERE name = 'A102 SMART CLASSROOM'         LIMIT 1), 'MEDIUM', 'Air Conditioning Not Cooling in A102',     'Room temperature remains high even after one hour.',                    'ticket002@smartcampus.com', 'IN_PROGRESS', (SELECT id FROM users WHERE email = 'nadeesha.peries@smartcampus.com' LIMIT 1), NULL,                                          NULL,                          NULL, NULL),
    ((SELECT id FROM users WHERE email = 'shehani.wickramasinghe@smartcampus.com' LIMIT 1), (SELECT id FROM assets WHERE name = 'A305 DESIGN STUDIO'           LIMIT 1), 'LOW',    'Drawing Tablets Need Driver Update',       'Several tablets disconnect randomly after login.',                      'ticket003@smartcampus.com', 'RESOLVED',    (SELECT id FROM users WHERE email = 'ruwan.fernando@smartcampus.com'  LIMIT 1), 'Updated drivers and restarted all devices.',  NULL,                          '2026-04-18 11:20:00', NULL),
    ((SELECT id FROM users WHERE email = 'dilan.gunasekara@smartcampus.com'       LIMIT 1), (SELECT id FROM assets WHERE name = 'C203 ELECTRONICS LAB'         LIMIT 1), 'HIGH',   'Soldering Station Fuse Tripping',          'Main soldering station trips power when heating starts.',               'ticket004@smartcampus.com', 'OPEN',        (SELECT id FROM users WHERE email = 'kavinda.mendis@smartcampus.com'  LIMIT 1), NULL,                                          NULL,                          NULL, NULL),
    ((SELECT id FROM users WHERE email = 'malith.senaratne@smartcampus.com'       LIMIT 1), (SELECT id FROM assets WHERE name = 'C110 SEMINAR ROOM'            LIMIT 1), 'MEDIUM', 'Wireless Microphone Interference',         'Audio cuts out every few minutes during presentations.',                'ticket005@smartcampus.com', 'CLOSED',      (SELECT id FROM users WHERE email = 'nadeesha.peries@smartcampus.com' LIMIT 1), 'Frequency channel adjusted and tested.',      NULL,                          '2026-04-17 10:10:00', '2026-04-17 16:45:00'),
    ((SELECT id FROM users WHERE email = 'pavithra.abeywickrama@smartcampus.com'  LIMIT 1), (SELECT id FROM assets WHERE name = 'D512 4K LASER PROJECTOR'      LIMIT 1), 'LOW',    'D512 Projector Focus Drift',               'Projected image loses focus after 15 minutes of use.',                  'ticket006@smartcampus.com', 'OPEN',        (SELECT id FROM users WHERE email = 'ruwan.fernando@smartcampus.com'  LIMIT 1), NULL,                                          NULL,                          NULL, NULL),
    ((SELECT id FROM users WHERE email = 'isuri.jayawardena@smartcampus.com'      LIMIT 1), (SELECT id FROM assets WHERE name = 'E904 AI INNOVATION HUB'       LIMIT 1), 'HIGH',   'GPU Workstation Overheating Alerts',       'Training machine shuts down under sustained load.',                     'ticket007@smartcampus.com', 'IN_PROGRESS', (SELECT id FROM users WHERE email = 'kavinda.mendis@smartcampus.com'  LIMIT 1), NULL,                                          NULL,                          NULL, NULL),
    ((SELECT id FROM users WHERE email = 'chamod.perera@smartcampus.com'          LIMIT 1), (SELECT id FROM assets WHERE name = 'F1102 INTERACTIVE PROJECTOR'  LIMIT 1), 'MEDIUM', 'F1102 Projector Remote Pairing Failure',   'The projector remote does not pair even after reset.',                  'ticket008@smartcampus.com', 'OPEN',        (SELECT id FROM users WHERE email = 'nadeesha.peries@smartcampus.com' LIMIT 1), NULL,                                          NULL,                          NULL, NULL),
    ((SELECT id FROM users WHERE email = 'shehani.wickramasinghe@smartcampus.com' LIMIT 1), (SELECT id FROM assets WHERE name = 'B702 NETWORK LAB'             LIMIT 1), 'LOW',    'Patch Panel Labels Missing',               'Multiple patch panel ports are unlabeled after rewiring.',              'ticket009@smartcampus.com', 'REJECTED',    (SELECT id FROM users WHERE email = 'ruwan.fernando@smartcampus.com'  LIMIT 1), NULL,                                          'Request lacks exact rack and port details.', NULL, NULL),
    ((SELECT id FROM users WHERE email = 'dilan.gunasekara@smartcampus.com'       LIMIT 1), (SELECT id FROM assets WHERE name = 'G1203 LINE ARRAY SOUND SYSTEM' LIMIT 1),'HIGH',   'G1203 Mixer Console Not Powering On',      'Main mixer remains offline and no output reaches speakers.',            'ticket010@smartcampus.com', 'OPEN',        (SELECT id FROM users WHERE email = 'kavinda.mendis@smartcampus.com'  LIMIT 1), NULL,                                          NULL,                          NULL, NULL);
